"""
Signal-level audit log — tracks every signal decision, not just trades.

This captures the full decision funnel:
  signal generated → pipeline filter → validation → sizing → execution
"""

from datetime import datetime, timezone

from sqlalchemy import DateTime, Float, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from alphaloop.db.models.base import Base


class SignalLog(Base):
    """Immutable record of every signal generated by the system."""

    __tablename__ = "signal_log"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)

    # Signal identification
    symbol: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    direction: Mapped[str] = mapped_column(String(4), nullable=False)
    signal_mode: Mapped[str] = mapped_column(
        String(20), nullable=False, default="ai"
    )  # ai, algorithmic, hybrid

    # Signal details
    confidence: Mapped[float | None] = mapped_column(Float, nullable=True)
    entry_lo: Mapped[float | None] = mapped_column(Float, nullable=True)
    entry_hi: Mapped[float | None] = mapped_column(Float, nullable=True)
    stop_loss: Mapped[float | None] = mapped_column(Float, nullable=True)
    take_profit_1: Mapped[float | None] = mapped_column(Float, nullable=True)
    take_profit_2: Mapped[float | None] = mapped_column(Float, nullable=True)
    setup_type: Mapped[str | None] = mapped_column(String(50), nullable=True)
    reasoning: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Decision outcome
    outcome: Mapped[str] = mapped_column(
        String(20), nullable=False, default="generated"
    )  # generated, pipeline_blocked, hard_rule_rejected, ai_rejected, validated, executed

    # Pipeline details
    blocked_by: Mapped[str | None] = mapped_column(String(50), nullable=True)
    rejection_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    size_modifier: Mapped[float | None] = mapped_column(Float, nullable=True)
    risk_score: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Context snapshot
    atr: Mapped[float | None] = mapped_column(Float, nullable=True)
    spread: Mapped[float | None] = mapped_column(Float, nullable=True)
    session_name: Mapped[str | None] = mapped_column(String(20), nullable=True)
    market_regime: Mapped[str | None] = mapped_column(String(20), nullable=True)

    # Metadata
    instance_id: Mapped[str | None] = mapped_column(String(50), nullable=True)
    strategy_version: Mapped[str | None] = mapped_column(String(20), nullable=True)
    model_used: Mapped[str | None] = mapped_column(String(50), nullable=True)
    latency_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        index=True,
    )
