"""Validator prompt templates for AI-based signal validation."""

import re

from alphaloop.config.assets import AssetConfig

_INJECTION_PATTERNS = re.compile(
    r"(ignore\s+(?:previous|all|prior)|override\s+(?:instructions?|rules?)|"
    r"instructions?:|system\s*prompt|forget\s+(?:previous|all)|"
    r"new\s+instructions?|disregard\s+(?:previous|all))",
    re.IGNORECASE,
)


def sanitize_reasoning(text: str) -> str:
    """Strip instruction-injection patterns from signal reasoning."""
    if not text:
        return text
    return _INJECTION_PATTERNS.sub("[REDACTED]", text)


def build_validator_system_prompt(
    asset: AssetConfig,
    *,
    min_rr: float = 1.5,
    min_confidence: float = 0.70,
    check_h1_trend: bool = True,
    check_news: bool = True,
    check_rsi: bool = True,
    rsi_ob: float = 75.0,
    rsi_os: float = 25.0,
    avoid_pre_news_minutes: int = 30,
) -> str:
    """Build an asset-aware system prompt for the validator model."""
    criteria = []
    criteria.append(f"1. Risk:Reward ratio >= {min_rr} to TP1")
    criteria.append(f"2. Confidence score >= {min_confidence:.2f}")
    n = 3
    if check_h1_trend:
        criteria.append(f"{n}. Higher timeframe (H1) must support the trade direction")
        n += 1
    if check_news:
        criteria.append(f"{n}. No high-impact news events within {avoid_pre_news_minutes} minutes")
        n += 1
    if check_rsi:
        criteria.append(f"{n}. RSI must not be extreme (no buys > {rsi_ob} RSI, no sells < {rsi_os} RSI on H1)")
        n += 1
    criteria.append(f"{n}. Liquidity sweep on lower TF adds significant conviction bonus")
    criteria.append(f"{n+1}. Entry zone must respect the asset's spread and volatility profile")
    criteria_text = "\n".join(criteria)

    return f"""You are a senior {asset.display_name} ({asset.symbol}) risk manager with a mandate to protect capital.
Your job is to VALIDATE trade signals generated by a signal engine for {asset.asset_class} markets.

Asset context: {asset.ai_context}

Your validation criteria (ALL must pass):
{criteria_text}

You MUST respond with ONLY valid JSON:
{{
  "status": "APPROVED" or "REJECTED",
  "rejection_reasons": ["reason1", "reason2"] or [],
  "adjusted_entry": null or price,
  "adjusted_sl": null or price,
  "adjusted_tp": null or [tp1, tp2],
  "risk_score": 0.0-1.0 (0=safest, 1=highest risk),
  "reasoning": "Your concise assessment"
}}

Be strict. Protecting capital is more important than finding trades.
Only approve setups where you see genuine edge. When in doubt, REJECT."""


def build_validation_prompt(
    signal,
    context: dict,
    asset: AssetConfig | None = None,
) -> str:
    """Build the validation request prompt."""
    h1_ind = context.get("timeframes", {}).get("H1", {}).get("indicators", {})
    news_events = context.get("upcoming_news", [])
    asset_label = asset.display_name if asset else "Asset"

    news_text = "  No high-impact events in window"
    if news_events:
        lines = []
        for ev in news_events:
            lines.append(f"  [{ev.get('impact', 'UNKNOWN')}] {ev.get('time')} — {ev.get('name')}")
        news_text = "\n".join(lines)

    return f"""=== {asset_label.upper()} TRADE SIGNAL VALIDATION REQUEST ===

SIGNAL TO VALIDATE:
  Direction: {signal.direction}
  Setup: {signal.setup.value}
  Entry Zone: {signal.entry_zone[0]} – {signal.entry_zone[1]}
  Stop Loss: {signal.stop_loss}
  Take Profit: {signal.take_profit}
  Confidence: {signal.confidence:.2f}
  R:R to TP1: {signal.rr_ratio_tp1}
  Signal Reasoning: {sanitize_reasoning(signal.reasoning)}

H1 CONTEXT (Higher Timeframe):
  EMA21: {h1_ind.get('ema21')} | EMA55: {h1_ind.get('ema55')} | EMA200: {h1_ind.get('ema200')}
  RSI: {h1_ind.get('rsi')} ({h1_ind.get('rsi_signal')})
  Trend Bias: {h1_ind.get('trend_bias')}
  ATR(H1): {h1_ind.get('atr')}

UPCOMING NEWS (next 2 hours):
{news_text}

MACRO SENTIMENT: {context.get('macro_sentiment', {}).get('bias', 'unknown').upper()}

Validate this signal now."""
