"""Validator prompt templates for AI-based signal validation."""

import re

from alphaloop.config.assets import AssetConfig

_INJECTION_PATTERNS = re.compile(
    r"(ignore\s+(?:previous|all|prior)|override\s+(?:instructions?|rules?)|"
    r"instructions?:|system\s*prompt|forget\s+(?:previous|all)|"
    r"new\s+instructions?|disregard\s+(?:previous|all))",
    re.IGNORECASE,
)


def sanitize_reasoning(text: str) -> str:
    """Strip instruction-injection patterns from signal reasoning."""
    if not text:
        return text
    return _INJECTION_PATTERNS.sub("[REDACTED]", text)


def build_validator_system_prompt(
    asset: AssetConfig,
    *,
    min_rr: float = 1.5,
    min_confidence: float = 0.70,
    check_h1_trend: bool = True,
    check_news: bool = True,
    check_rsi: bool = True,
    rsi_ob: float = 75.0,
    rsi_os: float = 25.0,
    avoid_pre_news_minutes: int = 30,
) -> str:
    """Build an asset-aware system prompt for the validator model."""
    secondary = []
    n = 4
    if check_h1_trend:
        secondary.append(f"{n}. H1 trend alignment (price on correct side of EMA200)")
        n += 1
    if check_rsi:
        secondary.append(f"{n}. RSI not extreme (no buys > {rsi_ob}, no sells < {rsi_os} on H1)")
        n += 1
    secondary.append(f"{n}. Confidence >= {min_confidence:.2f}")
    secondary.append(f"{n+1}. Session quality and spread within acceptable range")
    secondary_text = "\n".join(secondary) if secondary else ""

    return f"""You are a senior {asset.display_name} ({asset.symbol}) risk manager with a mandate to protect capital.
Your job is to VALIDATE trade signals generated by a signal engine for {asset.asset_class} markets.

Asset context: {asset.ai_context}

PRIMARY CHECKS (any single failure → REJECT immediately):
1. Risk:Reward ratio >= {min_rr} to TP1
2. Entry zone aligns with at least one M15 structural level (FVG, BOS, or key swing high/low within 0.5 ATR)
3. No high-impact or critical news event within {avoid_pre_news_minutes} minutes

SECONDARY CHECKS (combine for risk_score; poor secondary = high risk_score):
{secondary_text}

ENTRY STRUCTURE RULES:
- Entry inside an active FVG zone → PASS (structural support confirmed)
- Entry within 0.5 ATR of BOS level → PASS
- Entry with no nearby structural level → RED FLAG (raise risk_score significantly)

You MUST respond with ONLY valid JSON:
{{
  "status": "APPROVED" or "REJECTED",
  "rejection_reasons": ["reason1", "reason2"] or [],
  "adjusted_entry": null or price,
  "adjusted_sl": null or price,
  "adjusted_tp": null or [tp1, tp2],
  "risk_score": 0.0-1.0 (0=safest, 1=highest risk),
  "reasoning": "Your concise assessment"
}}

Be strict. Protecting capital is more important than finding trades.
Only approve setups where you see genuine edge. When in doubt, REJECT."""


def _fmt_m15_structure(m15_ind: dict, signal) -> str:
    """Format M15 structural context for the validator prompt."""
    bos = m15_ind.get("bos") or {}
    fvg = m15_ind.get("fvg") or {}
    atr = float(m15_ind.get("atr") or 0)

    # BOS info
    bos_dir = "none"
    bos_level = None
    if isinstance(bos, dict):
        if bos.get("bullish_bos"):
            bos_dir = "BULLISH"
            bos_level = bos.get("swing_high")
        elif bos.get("bearish_bos"):
            bos_dir = "BEARISH"
            bos_level = bos.get("swing_low")

    # FVG info — find most recent relevant zone
    entry_mid = None
    try:
        entry_mid = (float(signal.entry_zone[0]) + float(signal.entry_zone[1])) / 2
    except Exception:
        pass

    fvg_status = "NO FVG"
    fvg_zone = None
    if isinstance(fvg, dict) and entry_mid is not None:
        direction = getattr(signal, "direction", "BUY")
        fvg_list = fvg.get("bullish", []) if direction == "BUY" else fvg.get("bearish", [])
        if fvg_list:
            latest_fvg = fvg_list[-1]
            fvg_bot = float(latest_fvg.get("bottom", 0))
            fvg_top = float(latest_fvg.get("top", 0))
            fvg_zone = f"{fvg_bot}–{fvg_top}"
            if fvg_bot <= entry_mid <= fvg_top:
                fvg_status = "INSIDE FVG"
            elif entry_mid < fvg_bot:
                fvg_status = f"BELOW FVG ({round(fvg_bot - entry_mid, 2)} pts away)"
            else:
                fvg_status = f"ABOVE FVG ({round(entry_mid - fvg_top, 2)} pts away)"

    # BOS proximity
    bos_status = "no BOS"
    if bos_level is not None and entry_mid is not None and atr > 0:
        dist = abs(entry_mid - float(bos_level))
        atr_dist = round(dist / atr, 2)
        if atr_dist <= 0.5:
            bos_status = f"NEAR {bos_dir} BOS ({atr_dist} ATR)"
        else:
            bos_status = f"{bos_dir} BOS @ {bos_level} ({atr_dist} ATR away)"

    lines = [
        f"  Last BOS:   {bos_dir} @ {bos_level or 'N/A'}",
        f"  Active FVG: {fvg_zone or 'none'}",
        f"  Entry zone: {signal.entry_zone[0]} – {signal.entry_zone[1]}",
        f"  Entry vs FVG: {fvg_status}",
        f"  Entry vs BOS: {bos_status}",
    ]
    return "\n".join(lines)


def build_validation_prompt(
    signal,
    context: dict,
    asset: AssetConfig | None = None,
) -> str:
    """Build the validation request prompt with M15 structural context."""
    h1_ind = context.get("timeframes", {}).get("H1", {}).get("indicators", {})
    m15_ind = context.get("timeframes", {}).get("M15", {}).get("indicators", {})
    news_events = context.get("upcoming_news", [])
    asset_label = asset.display_name if asset else "Asset"

    # H1 trend bias (compute if missing)
    h1_trend = h1_ind.get("trend_bias", "N/A")
    h1_ema200 = h1_ind.get("ema200")
    price_raw = context.get("current_price") or context.get("price") or {}
    try:
        bid = float(price_raw.get("bid", 0) if isinstance(price_raw, dict) else getattr(price_raw, "bid", 0))
    except (TypeError, ValueError):
        bid = 0
    if h1_trend == "N/A" and h1_ema200 and bid > 0:
        h1_trend = "bullish" if bid > float(h1_ema200) else "bearish"

    news_text = "  No high-impact events in window"
    if news_events:
        lines = []
        for ev in news_events:
            lines.append(f"  [{ev.get('impact', 'UNKNOWN')}] {ev.get('time')} — {ev.get('name')}")
        news_text = "\n".join(lines)

    m15_structure = _fmt_m15_structure(m15_ind, signal)

    return f"""=== {asset_label.upper()} TRADE SIGNAL VALIDATION REQUEST ===

SIGNAL TO VALIDATE:
  Direction: {signal.direction}
  Setup: {signal.setup.value}
  Entry Zone: {signal.entry_zone[0]} – {signal.entry_zone[1]}
  Stop Loss: {signal.stop_loss}
  Take Profit: {signal.take_profit}
  Confidence: {signal.confidence:.2f}
  R:R to TP1: {signal.rr_ratio_tp1}
  Signal Reasoning: {sanitize_reasoning(signal.reasoning)}

M15 ENTRY STRUCTURE (cross-reference entry against structural levels):
{m15_structure}

H1 CONTEXT (Higher Timeframe):
  EMA_FAST: {h1_ind.get('ema_fast')} | EMA_SLOW: {h1_ind.get('ema_slow')} | EMA200: {h1_ema200}
  RSI: {h1_ind.get('rsi')} | Trend Bias: {h1_trend} | ATR: {h1_ind.get('atr')}

UPCOMING NEWS (next 2 hours):
{news_text}

MACRO SENTIMENT: {context.get('macro_sentiment', {}).get('bias', 'unknown').upper()}

Validate this signal now."""


# ── ALGO_AI scoring review prompts ──────────────────────────────────


def build_scoring_review_system_prompt(
    asset: AssetConfig,
) -> str:
    """System prompt for AI review of scoring engine decisions."""
    return f"""You are a senior {asset.display_name} ({asset.symbol}) risk manager reviewing a SCORED trade signal.

A probabilistic scoring engine has already analyzed {asset.asset_class} market data through 22 technical plugins grouped into 5 categories (trend, momentum, structure, volume, volatility). Each group outputs a 0-100 score. The groups are combined via weighted average into a total confidence score.

Your job is to REVIEW the scoring engine's output and decide whether to APPROVE, ADJUST, or VETO the trade.

You add value where indicators cannot:
- Cross-asset regime awareness (is the broader market environment hostile?)
- News/macro context that hasn't hit price yet
- Pattern quality judgment (is this a textbook setup or a marginal one?)
- Risk concentration (correlated positions, drawdown context)

You MUST respond with ONLY valid JSON:
{{
  "verdict": "APPROVE" or "ADJUST" or "VETO",
  "adjusted_confidence": null or 0-100 (only if verdict is ADJUST),
  "veto_reasons": ["reason1"] or [],
  "risk_score": 0.0-1.0 (0=safest, 1=highest risk),
  "reasoning": "Your concise assessment (2-3 sentences max)"
}}

Rules:
- APPROVE: scoring engine's decision stands as-is
- ADJUST: you agree with direction but want to modify confidence (affects position size)
- VETO: block the trade entirely (use sparingly — only for risks indicators cannot see)
- Do NOT second-guess indicator math. Your edge is context, not recalculating RSI.
- When in doubt between APPROVE and ADJUST, prefer ADJUST over VETO.
- Protecting capital is paramount. But excessive vetoing destroys the system's edge."""


def build_scoring_review_prompt(
    signal,
    context: dict,
    decision,
    feature_results: list,
    asset: AssetConfig | None = None,
) -> str:
    """
    Build the scoring review prompt with full scoring context.

    Args:
        signal: TradeSignal from algorithmic engine
        context: MarketContext dict
        decision: ScoringDecision from scoring engine
        feature_results: list[FeatureResult] from feature pipeline
        asset: AssetConfig for the symbol
    """
    asset_label = asset.display_name if asset else "Asset"

    # Group scores breakdown
    group_lines = []
    for group, score in sorted(decision.group_scores.items()):
        group_lines.append(f"  {group:12s}: {score:.1f}/100")
    group_text = "\n".join(group_lines) if group_lines else "  (no group scores)"

    # Per-plugin feature breakdown
    feature_lines = []
    for fr in feature_results:
        feats = " ".join(f"{k}={v:.1f}" for k, v in fr.features.items())
        feature_lines.append(f"  [{fr.group:10s}] {fr.tool_name:22s}: {feats}")
    feature_text = "\n".join(feature_lines) if feature_lines else "  (no features)"

    # Market context
    h1_ind = context.get("timeframes", {}).get("H1", {}).get("indicators", {})
    m15_ind = context.get("timeframes", {}).get("M15", {}).get("indicators", {})

    news_events = context.get("upcoming_news", [])
    news_text = "  None in window"
    if news_events:
        lines = []
        for ev in news_events:
            lines.append(f"  [{ev.get('impact', '?')}] {ev.get('time')} — {ev.get('name')}")
        news_text = "\n".join(lines)

    return f"""=== {asset_label.upper()} SCORING ENGINE REVIEW ===

DECISION:
  Direction: {decision.direction}
  Confidence: {decision.raw_confidence:.1f}/100
  Size Scalar: {decision.size_scalar:.2f}x
  Engine Reasoning: {decision.reasoning}

SIGNAL (from algorithmic engine):
  Direction: {signal.direction}
  Setup: {signal.setup.value}
  Entry Zone: {signal.entry_zone[0]} – {signal.entry_zone[1]}
  Stop Loss: {signal.stop_loss}
  Take Profit: {signal.take_profit}
  R:R to TP1: {signal.rr_ratio_tp1}

GROUP SCORES:
{group_text}

PLUGIN FEATURES (raw):
{feature_text}

H1 CONTEXT:
  EMA_FAST: {h1_ind.get('ema_fast')} | EMA_SLOW: {h1_ind.get('ema_slow')} | EMA200: {h1_ind.get('ema200')}
  RSI: {h1_ind.get('rsi')} | ADX: {h1_ind.get('adx')}
  Trend: {h1_ind.get('trend_bias')} | ATR: {h1_ind.get('atr')}

M15 CONTEXT:
  RSI: {m15_ind.get('rsi')} | ATR: {m15_ind.get('atr')}
  MACD Hist: {m15_ind.get('macd_histogram')}
  BB %B: {m15_ind.get('bb_pct_b')}

UPCOMING NEWS:
{news_text}

MACRO SENTIMENT: {context.get('macro_sentiment', {}).get('bias', 'unknown').upper()}

Review the scoring engine's decision now."""
